apiVersion: v2
name: umbrella-remote-example
version: 1.0.0

dependencies:
- name: hostinfo-2
  version: 1.0.0
  repository: "https://github.com/clacsinaRX-M/hostinfo-helm-2"
- name: hostinfo
  version: 1.0.0
  repository: "https://github.com/clacsinaRX-M/hostinfo-helm"
